/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import telefonia.Android;
import telefonia.Comerciales;
import telefonia.IOS;
import telefonia.Privado;
import telefonia.Telefonia;
import telefonia.Tradicional;
/**
 *
 * @author hernanBeiza
 */

//public class FonoBuscarFrame extends javax.swing.JFrame {
public class FonoBuscarFrame extends Ventana {

    private ArrayList<Telefonia> encontrados = null;
    /**
     * Creates new form FonoBuscar
     */
    public FonoBuscarFrame() {
        initComponents();
        iniciarCentrada();
        cargarMarcasAndroid();
        cboMarca.setEnabled(false);        
    }
   private void cargarMarcasAndroid(){
        String[] marcas = obtenerDB().getMarcasAndroid();
        DefaultComboBoxModel mdlCombo= (DefaultComboBoxModel)cboMarca.getModel();
        cboMarca.removeAllItems();
        for (String marca : marcas) {
            mdlCombo.addElement(marca);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filtroGrupo = new javax.swing.ButtonGroup();
        marcasCBO = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        datosTable = new javax.swing.JTable();
        buscarPanel = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        txtNumero = new javax.swing.JTextField();
        cboMarca = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        numeroRadio = new javax.swing.JRadioButton();
        rutRadio = new javax.swing.JRadioButton();
        marcaRadio = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        verDetalleButton = new javax.swing.JButton();
        volverButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BUSCAR TELEFONO ");

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        datosTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        datosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Rut", "Nombre", "Apellido", "Compañia", "Teléfono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        datosTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(datosTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        buscarPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        cboMarca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout buscarPanelLayout = new javax.swing.GroupLayout(buscarPanel);
        buscarPanel.setLayout(buscarPanelLayout);
        buscarPanelLayout.setHorizontalGroup(
            buscarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cboMarca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        buscarPanelLayout.setVerticalGroup(
            buscarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buscarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(cboMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        filtroGrupo.add(numeroRadio);
        numeroRadio.setSelected(true);
        numeroRadio.setText("Número");
        numeroRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroRadioActionPerformed(evt);
            }
        });

        filtroGrupo.add(rutRadio);
        rutRadio.setText("Rut");
        rutRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rutRadioActionPerformed(evt);
            }
        });

        filtroGrupo.add(marcaRadio);
        marcaRadio.setText("Marca");
        marcaRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcaRadioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(numeroRadio)
                .addGap(117, 117, 117)
                .addComponent(rutRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(marcaRadio)
                .addGap(74, 74, 74))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroRadio)
                    .addComponent(rutRadio)
                    .addComponent(marcaRadio))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        verDetalleButton.setText("Ver Detalle");
        verDetalleButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        verDetalleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verDetalleButtonActionPerformed(evt);
            }
        });

        volverButton.setText("Volver");
        volverButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        volverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(volverButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(verDetalleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(verDetalleButton, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addComponent(volverButton, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buscarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        //Revisar que tenga datos
        DefaultTableModel modeloTable = (DefaultTableModel) datosTable.getModel();
        int rowCount = modeloTable.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            modeloTable.removeRow(i);
        }
            
        encontrados = null;

        if(marcaRadio.isSelected()) {
            encontrados = obtenerDB().telefonosBuscarPorMarca(cboMarca.getSelectedItem().toString());            
        } else {
            if(!txtNumero.getText().equals("")){
                if(numeroRadio.isSelected()){                
                    encontrados = obtenerDB().telefonosBuscarPorNumero(txtNumero.getText());
                } else if(rutRadio.isSelected()){
                    encontrados = obtenerDB().telefonosBuscarPorRut(txtNumero.getText());
                }            
            } else {
                String mensaje ="Debe ingresar ";
                if(numeroRadio.isSelected()){
                    mensaje +="el número ";
                } else if(rutRadio.isSelected()){
                    mensaje +="el rut";
                }
                mensaje +=" para buscar";
                JOptionPane.showMessageDialog(rootPane, mensaje, "Error al intentar buscar", JOptionPane.WARNING_MESSAGE);
            }
        }
        
        if(encontrados.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "No se encontró el teléfono", "Error al intentar buscar", JOptionPane.ERROR_MESSAGE);
        } else {
            for (Telefonia unTelefono : encontrados) {
                modeloTable.addRow(new Object[]{unTelefono.getUsuario().getRun(),unTelefono.getUsuario().getNombre(),unTelefono.getUsuario().getApellido(),unTelefono.getCompania().getNombre(),unTelefono.getNumeroFono()});
            }
            datosTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void numeroRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroRadioActionPerformed
        // TODO add your handling code here:
        cboMarca.setEnabled(false);
        txtNumero.setEnabled(true);
     
    }//GEN-LAST:event_numeroRadioActionPerformed

    private void rutRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rutRadioActionPerformed
        // TODO add your handling code here:
        cboMarca.setEnabled(false);
        txtNumero.setEnabled(true);
  
    }//GEN-LAST:event_rutRadioActionPerformed

    private void marcaRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcaRadioActionPerformed
        // TODO add your handling code here:
        cboMarca.setEnabled(true);
        txtNumero.setEnabled(false);

        /*
        buscarPanel.remove(txtNumero);
        buscarPanel.add(marcasCBO);
        this.revalidate();
        this.repaint();
        */
    }//GEN-LAST:event_marcaRadioActionPerformed

    private void verDetalleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verDetalleButtonActionPerformed
        // TODO add your handling code here:
        System.out.println(datosTable.getSelectedRow());
        if(datosTable.getSelectedRow()>=0){
            int id = datosTable.getSelectedRow();
            System.out.println(id);
            final Telefonia telefono = encontrados.get(id);
            System.out.println(telefono.toString());
            
            java.awt.EventQueue.invokeLater(new Runnable() {
                @Override
                public void run() {
                    FonoEditarFrame editarFrame = new FonoEditarFrame();
                    editarFrame.setVisible(true);

                    if(telefono instanceof Privado){
                        System.out.println("Es un teléfono privado");
                        Privado unPrivado = (Privado)telefono;
                        editarFrame.cargarPrivado(unPrivado);
                    } else if(telefono instanceof Comerciales){
                        System.out.println("Es un teléfono comercial");
                        Comerciales unComercial = (Comerciales)telefono;
                        editarFrame.cargarComercial(unComercial);
                    } else if(telefono instanceof Android){
                        System.out.println("Es una mugre Android");
                        Android unAndroid = (Android)telefono;
                        editarFrame.cargarAndroid(unAndroid);
                    } else if(telefono instanceof IOS){
                        IOS unIOS = (IOS)telefono;
                        editarFrame.cargarIOS(unIOS);
                    } else if (telefono instanceof Tradicional){
                        System.out.println("Este lo usan los abuelitos Tradicional");
                    }            

                }
            });

            
        } else {
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar al menos una", "Error al ver detalle", JOptionPane.WARNING_MESSAGE);
        }        
    }//GEN-LAST:event_verDetalleButtonActionPerformed

    private void volverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_volverButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FonoBuscarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FonoBuscarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FonoBuscarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FonoBuscarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FonoBuscarFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JPanel buscarPanel;
    private javax.swing.JComboBox cboMarca;
    private javax.swing.JTable datosTable;
    private javax.swing.ButtonGroup filtroGrupo;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton marcaRadio;
    private javax.swing.JComboBox marcasCBO;
    private javax.swing.JRadioButton numeroRadio;
    private javax.swing.JRadioButton rutRadio;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JButton verDetalleButton;
    private javax.swing.JButton volverButton;
    // End of variables declaration//GEN-END:variables
}
