/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Component;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import telefonia.Compania;
import telefonia.PlanTelefonico;
import telefonia.Usuario;

/**
 *
 * @author Andres
 */
public class FonoAgregarFrameOLD extends Ventana {

    /**
     * Creates new form AgregarTelefonia
     */
    public FonoAgregarFrameOLD() {
        initComponents();
        iniciarCentrada();
        cargarInfoCompania();
        //Prueba de uso
        bloquearTab(0);
        bloquearTab(1);
        bloquearTab(2);
        bloquearTab(3);
        desbloquearTab(1);
    }
    
    private void bloquearTab(int indice){
        TabSmart.setEnabledAt(indice, false);
        JPanel panel = null;
        switch(indice){
            case 0:
                panel = JPPrivado;
                break;
            case 1:
                panel = JPComercial;
                break;
            case 2:
                panel = JPTradicional;
                break;
            case 3:
                panel = JPSmartphone;
                break;
        }
        for (Component component : panel.getComponents()) {
            //System.out.println(component);
            Component unComponente = component;
            unComponente.setEnabled(false);
        }
    }
    
    private void desbloquearTab(int indice){
        TabSmart.setEnabledAt(indice, true);
        TabSmart.setSelectedIndex(indice);
        JPanel panel = null;
        switch(indice){
            case 0:
                panel = JPPrivado;
                break;
            case 1:
                panel = JPComercial;
                break;
            case 2:
                panel = JPTradicional;
                break;
            case 3:
                panel = JPSmartphone;
                break;
        }
  
        for (Component component : panel.getComponents()) {
            //System.out.println(component);
            Component unComponente = component;
            unComponente.setEnabled(true);
        }        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        SmarthGroup = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        lblCompañia = new javax.swing.JLabel();
        CmbCompañia = new javax.swing.JComboBox();
        LblRut = new javax.swing.JLabel();
        TxtRut = new javax.swing.JTextField();
        LblFono = new javax.swing.JLabel();
        TxtFono = new javax.swing.JTextField();
        LblNombre = new javax.swing.JLabel();
        LblComuna = new javax.swing.JLabel();
        TxtComuna = new javax.swing.JTextField();
        LblRegion = new javax.swing.JLabel();
        LblContrato = new javax.swing.JLabel();
        TxtFechadeContrato = new javax.swing.JTextField();
        LblCosto = new javax.swing.JLabel();
        TxtCostoEquipo = new javax.swing.JTextField();
        LblPlanT = new javax.swing.JLabel();
        CmbPlanTelefonico = new javax.swing.JComboBox();
        CmbRegion = new javax.swing.JComboBox();
        TabSmart = new javax.swing.JTabbedPane();
        JPPrivado = new javax.swing.JPanel();
        LblIdentifLlamadas = new javax.swing.JLabel();
        CmbIdeLlamadas = new javax.swing.JComboBox();
        JPComercial = new javax.swing.JPanel();
        LblCantidadAnexos = new javax.swing.JLabel();
        CmbAnexos = new javax.swing.JComboBox();
        JPTradicional = new javax.swing.JPanel();
        RbtNormal = new javax.swing.JRadioButton();
        RbtSlide = new javax.swing.JRadioButton();
        RbtAlmeja = new javax.swing.JRadioButton();
        LblPantallaColor = new javax.swing.JLabel();
        CmbPantallaColor = new javax.swing.JComboBox();
        JPSmartphone = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        RbtIphone = new javax.swing.JRadioButton();
        RbtAndroid = new javax.swing.JRadioButton();
        LblSop = new javax.swing.JLabel();
        CmbSop = new javax.swing.JComboBox();
        LblMemoriaIphone = new javax.swing.JLabel();
        CmbMemoriaIphone = new javax.swing.JComboBox();
        LblModelo = new javax.swing.JLabel();
        CmbModelo = new javax.swing.JComboBox();
        LblMarca = new javax.swing.JLabel();
        CmbMarca = new javax.swing.JComboBox();
        LblMemoriaAndroid = new javax.swing.JLabel();
        CmbMemoriaAndroid = new javax.swing.JComboBox();
        LblDuracionBateria = new javax.swing.JLabel();
        CmbDuración1 = new javax.swing.JComboBox();
        LblPeso = new javax.swing.JLabel();
        CmbPeso1 = new javax.swing.JComboBox();
        jPanel11 = new javax.swing.JPanel();
        LblValorMinutoFijo1 = new javax.swing.JLabel();
        TxtValorMinutoFijo1 = new javax.swing.JTextField();
        LblValorMinutoMovil1 = new javax.swing.JLabel();
        TxtValorMinutoMovil1 = new javax.swing.JTextField();
        LblTarifaFija1 = new javax.swing.JLabel();
        LblMinutosUsadosFijo1 = new javax.swing.JLabel();
        TxtMinutosUsadosFijo1 = new javax.swing.JTextField();
        TxtTarifaFija1 = new javax.swing.JTextField();
        LblMinutosUsadosMovil1 = new javax.swing.JLabel();
        TxtMinutosUsadosMovil1 = new javax.swing.JTextField();
        BtnCerrar = new javax.swing.JButton();

        menu1.setLabel("File");
        menu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu1ActionPerformed(evt);
            }
        });
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INGRESO TELEFONIA");

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblCompañia.setText("Compañia");

        CmbCompañia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CmbCompañiaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CmbCompañiaMousePressed(evt);
            }
        });
        CmbCompañia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbCompañiaActionPerformed(evt);
            }
        });

        LblRut.setText("Rut");

        TxtRut.setText("13269946-1");
        TxtRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtRutActionPerformed(evt);
            }
        });
        TxtRut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtRutKeyPressed(evt);
            }
        });

        LblFono.setText("Numero Telefono ");

        TxtFono.setText("0225430903");
        TxtFono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFonoActionPerformed(evt);
            }
        });
        TxtFono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtFonoKeyPressed(evt);
            }
        });

        LblNombre.setText("-");

        LblComuna.setText("Comuna");

        TxtComuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtComunaActionPerformed(evt);
            }
        });
        TxtComuna.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtComunaKeyPressed(evt);
            }
        });

        LblRegion.setText("Región");

        LblContrato.setText("Fecha Contrato");

        TxtFechadeContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFechadeContratoActionPerformed(evt);
            }
        });

        LblCosto.setText("Costo Equipo");

        TxtCostoEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCostoEquipoActionPerformed(evt);
            }
        });

        LblPlanT.setText("Plan Telefonico");

        CmbPlanTelefonico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbPlanTelefonicoActionPerformed(evt);
            }
        });

        CmbRegion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Arica y Parinacota", "Tarapacá", "Antofagasta", "Atacama", "Coquimbo", "Valparaíso", "Libertador General", "Bernardo O'Higgins", "Maule", "Biobío", "Araucanía", "Los Ríos", "Los Lagos", "Aysén del General", "Carlos Ibáñez del Campo", "Magallanes y de la", "Antártica Chilena", "Metropolitana de SantiagoArica y Parinacota" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(LblComuna)
                            .addGap(26, 26, 26)
                            .addComponent(TxtComuna, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(LblRegion)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(CmbRegion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(lblCompañia)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(CmbCompañia, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(LblContrato)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TxtFechadeContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(LblCosto)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TxtCostoEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(LblPlanT)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(CmbPlanTelefonico, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(LblRut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtRut, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(LblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LblFono)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtFono, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblRut)
                    .addComponent(TxtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblFono)
                    .addComponent(TxtFono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblComuna)
                    .addComponent(TxtComuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblRegion)
                    .addComponent(CmbRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CmbCompañia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblContrato)
                    .addComponent(TxtFechadeContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblCosto)
                    .addComponent(TxtCostoEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCompañia))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblPlanT)
                    .addComponent(CmbPlanTelefonico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        TabSmart.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TabSmart.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        JPPrivado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JPPrivado.setEnabled(false);

        LblIdentifLlamadas.setText("Identificador de Llamadas");

        CmbIdeLlamadas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SI", "NO" }));

        javax.swing.GroupLayout JPPrivadoLayout = new javax.swing.GroupLayout(JPPrivado);
        JPPrivado.setLayout(JPPrivadoLayout);
        JPPrivadoLayout.setHorizontalGroup(
            JPPrivadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPPrivadoLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(LblIdentifLlamadas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CmbIdeLlamadas, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(213, Short.MAX_VALUE))
        );
        JPPrivadoLayout.setVerticalGroup(
            JPPrivadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPPrivadoLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(JPPrivadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblIdentifLlamadas)
                    .addComponent(CmbIdeLlamadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        TabSmart.addTab("Privado", JPPrivado);

        JPComercial.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JPComercial.setEnabled(false);

        LblCantidadAnexos.setText("Cantidad de Anexos");

        CmbAnexos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10", "20", "30", "40", "50", "60", "70", "80", "90", "100" }));

        javax.swing.GroupLayout JPComercialLayout = new javax.swing.GroupLayout(JPComercial);
        JPComercial.setLayout(JPComercialLayout);
        JPComercialLayout.setHorizontalGroup(
            JPComercialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPComercialLayout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(LblCantidadAnexos, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CmbAnexos, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(210, Short.MAX_VALUE))
        );
        JPComercialLayout.setVerticalGroup(
            JPComercialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPComercialLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(JPComercialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblCantidadAnexos)
                    .addComponent(CmbAnexos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        TabSmart.addTab("Comercial", JPComercial);

        JPTradicional.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JPTradicional.setEnabled(false);

        SmarthGroup.add(RbtNormal);
        RbtNormal.setText("Normal");

        SmarthGroup.add(RbtSlide);
        RbtSlide.setText("Slide");

        SmarthGroup.add(RbtAlmeja);
        RbtAlmeja.setText("Almeja");

        LblPantallaColor.setText("Pantalla Color");

        CmbPantallaColor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SI", "NO" }));

        javax.swing.GroupLayout JPTradicionalLayout = new javax.swing.GroupLayout(JPTradicional);
        JPTradicional.setLayout(JPTradicionalLayout);
        JPTradicionalLayout.setHorizontalGroup(
            JPTradicionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPTradicionalLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(RbtNormal)
                .addGap(138, 138, 138)
                .addComponent(RbtSlide)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RbtAlmeja)
                .addGap(89, 89, 89))
            .addGroup(JPTradicionalLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(LblPantallaColor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CmbPantallaColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(256, Short.MAX_VALUE))
        );
        JPTradicionalLayout.setVerticalGroup(
            JPTradicionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPTradicionalLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(JPTradicionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblPantallaColor)
                    .addComponent(CmbPantallaColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(JPTradicionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RbtNormal)
                    .addComponent(RbtSlide)
                    .addComponent(RbtAlmeja))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        TabSmart.addTab("Tradicional", JPTradicional);

        JPSmartphone.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JPSmartphone.setEnabled(false);

        SmarthGroup.add(RbtIphone);
        RbtIphone.setText(" Iphone");
        RbtIphone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RbtIphoneMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RbtIphoneMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                RbtIphoneMouseReleased(evt);
            }
        });
        RbtIphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtIphoneActionPerformed(evt);
            }
        });
        RbtIphone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                RbtIphoneKeyPressed(evt);
            }
        });

        SmarthGroup.add(RbtAndroid);
        RbtAndroid.setText("Android");
        RbtAndroid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RbtAndroidMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                RbtAndroidMouseReleased(evt);
            }
        });

        LblSop.setText("Sistema Operativo");

        CmbSop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "7.0", "8.0", "9.0" }));
        CmbSop.setEnabled(false);

        LblMemoriaIphone.setText("Memoria");

        CmbMemoriaIphone.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "16", "32", "36", "128" }));
        CmbMemoriaIphone.setEnabled(false);

        LblModelo.setText("Modelo");

        CmbModelo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6" }));
        CmbModelo.setEnabled(false);

        LblMarca.setText("Marca");

        CmbMarca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "7.0", "8.0", "9.0" }));
        CmbMarca.setEnabled(false);

        LblMemoriaAndroid.setText("Memoria");

        CmbMemoriaAndroid.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "16", "32", "36", "128" }));
        CmbMemoriaAndroid.setEnabled(false);

        LblDuracionBateria.setText("Duración Bateria");

        CmbDuración1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6" }));
        CmbDuración1.setEnabled(false);

        LblPeso.setText("Peso");

        CmbPeso1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "100 Gr", "200 Gr", "300 Gr", "400 Gr" }));
        CmbPeso1.setEnabled(false);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(RbtIphone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RbtAndroid)
                        .addGap(68, 68, 68))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(LblSop)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CmbSop, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(LblMemoriaIphone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CmbMemoriaIphone, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(LblModelo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CmbModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(LblMarca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CmbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(LblMemoriaAndroid)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CmbMemoriaAndroid, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(LblDuracionBateria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CmbDuración1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(LblPeso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CmbPeso1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RbtIphone)
                    .addComponent(RbtAndroid))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblSop)
                    .addComponent(CmbSop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblMarca)
                    .addComponent(CmbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblMemoriaIphone)
                            .addComponent(CmbMemoriaIphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblModelo)
                            .addComponent(CmbModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblMemoriaAndroid)
                            .addComponent(CmbMemoriaAndroid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblDuracionBateria)
                            .addComponent(CmbDuración1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblPeso)
                            .addComponent(CmbPeso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JPSmartphoneLayout = new javax.swing.GroupLayout(JPSmartphone);
        JPSmartphone.setLayout(JPSmartphoneLayout);
        JPSmartphoneLayout.setHorizontalGroup(
            JPSmartphoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPSmartphoneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPSmartphoneLayout.setVerticalGroup(
            JPSmartphoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPSmartphoneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TabSmart.addTab("SmartPhone", JPSmartphone);

        jPanel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        LblValorMinutoFijo1.setText("Valor Minuto Fijo");

        TxtValorMinutoFijo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtValorMinutoFijo1ActionPerformed(evt);
            }
        });

        LblValorMinutoMovil1.setText("Valor Minuto Movil");

        LblTarifaFija1.setText("Tarifa Fija");

        LblMinutosUsadosFijo1.setText("Cantidad Minutos Usados Fijos");

        LblMinutosUsadosMovil1.setText("Cantidad Minutos Usados Moviles");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(LblValorMinutoFijo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TxtValorMinutoFijo1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LblValorMinutoMovil1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtValorMinutoMovil1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LblTarifaFija1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtTarifaFija1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(567, 567, 567))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(LblMinutosUsadosFijo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtMinutosUsadosFijo1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LblMinutosUsadosMovil1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtMinutosUsadosMovil1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblValorMinutoFijo1)
                    .addComponent(TxtValorMinutoFijo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblValorMinutoMovil1)
                    .addComponent(TxtValorMinutoMovil1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblTarifaFija1)
                    .addComponent(TxtTarifaFija1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblMinutosUsadosFijo1)
                    .addComponent(TxtMinutosUsadosFijo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblMinutosUsadosMovil1)
                    .addComponent(TxtMinutosUsadosMovil1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        BtnCerrar.setText("Cerrar");
        BtnCerrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(TabSmart, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(BtnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TabSmart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TabSmart.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RbtIphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtIphoneActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_RbtIphoneActionPerformed

    private void RbtIphoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RbtIphoneMouseClicked
        // TODO add your handling code here:
            this.CmbSop.setEnabled(true);
            this.CmbMemoriaIphone.setEnabled(true);
            this.CmbModelo.setEnabled(true);
            
            this.CmbMarca.setEnabled(false);
            this.CmbMemoriaAndroid.setEnabled(false);
            this.CmbPeso1.setEnabled(false);
            this.CmbDuración1.setEnabled(false);

    }//GEN-LAST:event_RbtIphoneMouseClicked

    private void RbtIphoneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RbtIphoneMousePressed
        // TODO add your handling code here
    }//GEN-LAST:event_RbtIphoneMousePressed

    private void RbtIphoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RbtIphoneKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_RbtIphoneKeyPressed

    private void RbtAndroidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RbtAndroidMouseClicked
        // TODO add your handling code here:
            this.CmbSop.setEnabled(false);
            this.CmbMemoriaIphone.setEnabled(false);
            this.CmbModelo.setEnabled(false);
            
            this.CmbMarca.setEnabled(true);
            this.CmbMemoriaAndroid.setEnabled(true);
            this.CmbPeso1.setEnabled(true);
            this.CmbDuración1.setEnabled(true);
            
    }//GEN-LAST:event_RbtAndroidMouseClicked

    private void RbtIphoneMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RbtIphoneMouseReleased
        // TODO add your handling code here:
            this.CmbSop.setEnabled(true);
            this.CmbMemoriaIphone.setEnabled(true);
            this.CmbModelo.setEnabled(true);
            
            this.CmbMarca.setEnabled(false);
            this.CmbMemoriaAndroid.setEnabled(false);
            this.CmbPeso1.setEnabled(false);
            this.CmbDuración1.setEnabled(false);

    }//GEN-LAST:event_RbtIphoneMouseReleased

    private void RbtAndroidMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RbtAndroidMouseReleased
        // TODO add your handling code here:
            this.CmbSop.setEnabled(false);
            this.CmbMemoriaIphone.setEnabled(false);
            this.CmbModelo.setEnabled(false);
            
            this.CmbMarca.setEnabled(true);
            this.CmbMemoriaAndroid.setEnabled(true);
            this.CmbPeso1.setEnabled(true);
            this.CmbDuración1.setEnabled(true);        
    }//GEN-LAST:event_RbtAndroidMouseReleased

    private void BtnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_BtnCerrarActionPerformed

    private void CmbPlanTelefonicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbPlanTelefonicoActionPerformed
        // TODO add your handling code here:
        CmbPlanTelefonico.transferFocus();
    }//GEN-LAST:event_CmbPlanTelefonicoActionPerformed

    private void TxtRutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtRutKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TxtRutKeyPressed

    private void TxtRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtRutActionPerformed
        // TODO add your handling code here:
        this.TxtRut.transferFocus();

        //int NomUsu = CmbCompañia.getSelectedIndex();
        String RutUsu = TxtRut.getText();
        Usuario Obj_Usuario = obtenerDB().usuarioBuscarPorRut(RutUsu);
        System.out.println(Obj_Usuario);
                    String Nombre = Obj_Usuario.getNombre() +" "+Obj_Usuario.getApellido(); 
                    System.out.println("Nombre Usuario "+Nombre);
                    LblNombre.setText(Nombre);

        
        //aca agregar que lea de la tabla usuarios y rescate el nombre 
            
    }//GEN-LAST:event_TxtRutActionPerformed

    private void TxtFonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFonoActionPerformed
        // TODO add your handling code here:
        this.TxtFono.transferFocus();
        
     
        
    }//GEN-LAST:event_TxtFonoActionPerformed

    private void TxtComunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtComunaActionPerformed
        // TODO add your handling code here:}
        this.TxtComuna.transferFocus();
        
    }//GEN-LAST:event_TxtComunaActionPerformed

    private void CmbCompañiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbCompañiaActionPerformed
        // TODO add your handling code here:
        CmbCompañia.transferFocus();
        CmbPlanTelefonico.removeAllItems();
        int NomCom = CmbCompañia.getSelectedIndex();
        Compania Paso = obtenerDB().companiaObtener().get(NomCom);
      
        DefaultComboBoxModel mdlCombo= (DefaultComboBoxModel)CmbPlanTelefonico.getModel();
                        Iterator it = Paso.getPlan().iterator();
                        int rowCount = mdlCombo.getSize();
                        for (int i = rowCount - 1; i >= 0; i--) {
                            mdlCombo.removeElement(i);
                        }
               while(it.hasNext()){
                PlanTelefonico plan = (PlanTelefonico)it.next();
                String NombrePlan = plan.getNombrePlan();
                mdlCombo.addElement(NombrePlan);
                System.out.println("nombre plan "+plan.getNombrePlan());
               }

    }//GEN-LAST:event_CmbCompañiaActionPerformed

    private void TxtFechadeContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFechadeContratoActionPerformed
        // TODO add your handling code here:
        TxtFechadeContrato.transferFocus();
    }//GEN-LAST:event_TxtFechadeContratoActionPerformed

    private void TxtCostoEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCostoEquipoActionPerformed
        // TODO add your handling code here:
        TxtCostoEquipo.transferFocus();
    }//GEN-LAST:event_TxtCostoEquipoActionPerformed

    private void TxtComunaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtComunaKeyPressed
        // TODO add your handling code here:
//               TransformaMayuscula(TxtComuna.getText());
    }//GEN-LAST:event_TxtComunaKeyPressed

    private void TxtFonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtFonoKeyPressed
        // TODO add your handling code here:
    String numero = this.TxtFono.getText();
     //   esMovil(numero);
        
        if (obtenerDB().telefonosEsMovil(numero)){
            System.out.println("false");
        }else{
    
            System.out.println("true");
//        TabSmart.setEnabledAt(0, true);
//        int p = TabSmart.getTabCount();
//            System.out.println(p);
//            for (int i = 0; i<p;i++){
//                    System.out.println(TabSmart.isEnabledAt(i));
//            }
        }
/// agregar validacion fojos o moviles
    }//GEN-LAST:event_TxtFonoKeyPressed

    private void TxtValorMinutoFijo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtValorMinutoFijo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtValorMinutoFijo1ActionPerformed

    private void CmbCompañiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CmbCompañiaMouseClicked

    }//GEN-LAST:event_CmbCompañiaMouseClicked

    private void CmbCompañiaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CmbCompañiaMousePressed
    // TODO add your handling code here:
        //aca mejor

    }//GEN-LAST:event_CmbCompañiaMousePressed

    private void menu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FonoAgregarFrameOLD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FonoAgregarFrameOLD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FonoAgregarFrameOLD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FonoAgregarFrameOLD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FonoAgregarFrameOLD().setVisible(true);
            }
        });
    }
 
   private void cargarInfoCompania(){
       ArrayList <Compania> compania = obtenerDB().companiaObtener();
        System.out.println(compania.toString());
        if(compania.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "No se encontraron planes", "Error al intentar listar", JOptionPane.WARNING_MESSAGE);
        } else {
            DefaultComboBoxModel mdlCombo= (DefaultComboBoxModel)CmbCompañia.getModel();
            Iterator it = compania.iterator();
            int rowCount = mdlCombo.getSize();
            for (int i = rowCount - 1; i >= 0; i--) {
                mdlCombo.removeElement(i);
            }
            while(it.hasNext()){

                Compania Obj_Compania = (Compania)it.next();
                String Comp = Obj_Compania.getNombre();
                mdlCombo.addElement(Comp);
                System.out.println("nombre plan "+Obj_Compania.getNombre());
             }
        }
  }
   
 
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCerrar;
    private javax.swing.JComboBox CmbAnexos;
    private javax.swing.JComboBox CmbCompañia;
    private javax.swing.JComboBox CmbDuración1;
    private javax.swing.JComboBox CmbIdeLlamadas;
    private javax.swing.JComboBox CmbMarca;
    private javax.swing.JComboBox CmbMemoriaAndroid;
    private javax.swing.JComboBox CmbMemoriaIphone;
    private javax.swing.JComboBox CmbModelo;
    private javax.swing.JComboBox CmbPantallaColor;
    private javax.swing.JComboBox CmbPeso1;
    private javax.swing.JComboBox CmbPlanTelefonico;
    private javax.swing.JComboBox CmbRegion;
    private javax.swing.JComboBox CmbSop;
    private javax.swing.JPanel JPComercial;
    private javax.swing.JPanel JPPrivado;
    private javax.swing.JPanel JPSmartphone;
    private javax.swing.JPanel JPTradicional;
    private javax.swing.JLabel LblCantidadAnexos;
    private javax.swing.JLabel LblComuna;
    private javax.swing.JLabel LblContrato;
    private javax.swing.JLabel LblCosto;
    private javax.swing.JLabel LblDuracionBateria;
    private javax.swing.JLabel LblFono;
    private javax.swing.JLabel LblIdentifLlamadas;
    private javax.swing.JLabel LblMarca;
    private javax.swing.JLabel LblMemoriaAndroid;
    private javax.swing.JLabel LblMemoriaIphone;
    private javax.swing.JLabel LblMinutosUsadosFijo1;
    private javax.swing.JLabel LblMinutosUsadosMovil1;
    private javax.swing.JLabel LblModelo;
    private javax.swing.JLabel LblNombre;
    private javax.swing.JLabel LblPantallaColor;
    private javax.swing.JLabel LblPeso;
    private javax.swing.JLabel LblPlanT;
    private javax.swing.JLabel LblRegion;
    private javax.swing.JLabel LblRut;
    private javax.swing.JLabel LblSop;
    private javax.swing.JLabel LblTarifaFija1;
    private javax.swing.JLabel LblValorMinutoFijo1;
    private javax.swing.JLabel LblValorMinutoMovil1;
    private javax.swing.JRadioButton RbtAlmeja;
    private javax.swing.JRadioButton RbtAndroid;
    private javax.swing.JRadioButton RbtIphone;
    private javax.swing.JRadioButton RbtNormal;
    private javax.swing.JRadioButton RbtSlide;
    private javax.swing.ButtonGroup SmarthGroup;
    private javax.swing.JTabbedPane TabSmart;
    private javax.swing.JTextField TxtComuna;
    private javax.swing.JTextField TxtCostoEquipo;
    private javax.swing.JTextField TxtFechadeContrato;
    private javax.swing.JTextField TxtFono;
    private javax.swing.JTextField TxtMinutosUsadosFijo1;
    private javax.swing.JTextField TxtMinutosUsadosMovil1;
    private javax.swing.JTextField TxtRut;
    private javax.swing.JTextField TxtTarifaFija1;
    private javax.swing.JTextField TxtValorMinutoFijo1;
    private javax.swing.JTextField TxtValorMinutoMovil1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCompañia;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    // End of variables declaration//GEN-END:variables
}
