/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import javax.swing.JOptionPane;
import telefonia.DB;

/**
 *
 * @author hernanBeiza
 */
public class MainFrame extends javax.swing.JFrame {

    private DB db;

    /**
     * Creates new form MainFrame
     */
    
    public MainFrame() {
        initComponents();
        db = new DB();
        db.iniciarData();
        
        setExtendedState(MAXIMIZED_BOTH);
    }

    public DB getDb() {
        return db;
    }

    public void setDb(DB db) {
        this.db = db;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        usuariosMenu = new javax.swing.JMenu();
        usuariosAgregarMenuItem = new javax.swing.JMenuItem();
        usuariosListarMenuItem = new javax.swing.JMenuItem();
        planesMenu = new javax.swing.JMenu();
        companiaMenu = new javax.swing.JMenu();
        companiaAgregarMenuItem = new javax.swing.JMenuItem();
        companiaConsultarMenuItem = new javax.swing.JMenuItem();
        telefonosMenu = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        buscarNumeroItem = new javax.swing.JMenuItem();
        eliminarNumeroItem = new javax.swing.JMenuItem();
        cantidadMenuItem = new javax.swing.JMenuItem();
        cuentasMenu = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        servicioMenu = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        salirMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(630, 400));

        usuariosMenu.setText("Usuarios");

        usuariosAgregarMenuItem.setText("Agregar usuario");
        usuariosAgregarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariosAgregarMenuItemActionPerformed(evt);
            }
        });
        usuariosMenu.add(usuariosAgregarMenuItem);

        usuariosListarMenuItem.setText("Listar usuarios");
        usuariosListarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariosListarMenuItemActionPerformed(evt);
            }
        });
        usuariosMenu.add(usuariosListarMenuItem);

        jMenuBar1.add(usuariosMenu);

        planesMenu.setText("Planes Telefónicos");
        jMenuBar1.add(planesMenu);

        companiaMenu.setText("Compañia");

        companiaAgregarMenuItem.setText("Agregar compañía");
        companiaAgregarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companiaAgregarMenuItemActionPerformed(evt);
            }
        });
        companiaMenu.add(companiaAgregarMenuItem);

        companiaConsultarMenuItem.setText("Listar compañías");
        companiaConsultarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companiaConsultarMenuItemActionPerformed(evt);
            }
        });
        companiaMenu.add(companiaConsultarMenuItem);

        jMenuBar1.add(companiaMenu);

        telefonosMenu.setText("Teléfonos");

        jMenuItem8.setText("Agregar teléfono");
        telefonosMenu.add(jMenuItem8);

        buscarNumeroItem.setText("Buscar teléfono");
        buscarNumeroItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarNumeroItemActionPerformed(evt);
            }
        });
        telefonosMenu.add(buscarNumeroItem);

        eliminarNumeroItem.setText("Eliminar teléfono");
        eliminarNumeroItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarNumeroItemActionPerformed(evt);
            }
        });
        telefonosMenu.add(eliminarNumeroItem);

        cantidadMenuItem.setText("Cantidad números privados");
        cantidadMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadMenuItemActionPerformed(evt);
            }
        });
        telefonosMenu.add(cantidadMenuItem);

        jMenuBar1.add(telefonosMenu);

        cuentasMenu.setText("Cuentas");

        jMenuItem3.setText("Mostrar cuenta");
        cuentasMenu.add(jMenuItem3);

        jMenuItem4.setText("Mostrar cuenta simple");
        cuentasMenu.add(jMenuItem4);

        jMenuItem5.setText("Cantidad de cuentas sobre 250 minutos");
        cuentasMenu.add(jMenuItem5);

        jMenuBar1.add(cuentasMenu);

        servicioMenu.setText("Servicio Técnico");

        jMenuItem6.setText("Aplicar servicio a un teléfono");
        servicioMenu.add(jMenuItem6);

        jMenuItem7.setText("Buscar teléfonos llevados al servicio técnico");
        servicioMenu.add(jMenuItem7);

        jMenuBar1.add(servicioMenu);

        salirMenu.setText("Salir");
        salirMenu.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                salirMenuMenuSelected(evt);
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
        });
        jMenuBar1.add(salirMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarNumeroItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarNumeroItemActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FonoBuscarFrame().setVisible(true);
            }
        });
    }//GEN-LAST:event_buscarNumeroItemActionPerformed

    private void eliminarNumeroItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarNumeroItemActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FonoEliminarFrame().setVisible(true);
            }
        });
    }//GEN-LAST:event_eliminarNumeroItemActionPerformed

    private void cantidadMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadMenuItemActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FonoCantidadFrame().setVisible(true);
            }
        });
    }//GEN-LAST:event_cantidadMenuItemActionPerformed

    private void salirMenuMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_salirMenuMenuSelected
        int dialogButton = JOptionPane.showConfirmDialog (rootPane, "¿Está seguro que desea cerrar el programa?","¿Está seguro?", JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
        if(dialogButton==0){
            System.exit(0);
        }
    }//GEN-LAST:event_salirMenuMenuSelected

    private void usuariosAgregarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariosAgregarMenuItemActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsuarioAgregarFrame().setVisible(true);
            }
        });
    }//GEN-LAST:event_usuariosAgregarMenuItemActionPerformed

    private void usuariosListarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariosListarMenuItemActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsuarioListarFrame().setVisible(true);
            }
        });
    }//GEN-LAST:event_usuariosListarMenuItemActionPerformed

    private void companiaConsultarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companiaConsultarMenuItemActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompaniaConsultarFrame().setVisible(true);
            }
        });
    }//GEN-LAST:event_companiaConsultarMenuItemActionPerformed

    private void companiaAgregarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companiaAgregarMenuItemActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompaniaAgregarFrame().setVisible(true);
            }
        });
    }//GEN-LAST:event_companiaAgregarMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem buscarNumeroItem;
    private javax.swing.JMenuItem cantidadMenuItem;
    private javax.swing.JMenuItem companiaAgregarMenuItem;
    private javax.swing.JMenuItem companiaConsultarMenuItem;
    private javax.swing.JMenu companiaMenu;
    private javax.swing.JMenu cuentasMenu;
    private javax.swing.JMenuItem eliminarNumeroItem;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenu planesMenu;
    private javax.swing.JMenu salirMenu;
    private javax.swing.JMenu servicioMenu;
    private javax.swing.JMenu telefonosMenu;
    private javax.swing.JMenuItem usuariosAgregarMenuItem;
    private javax.swing.JMenuItem usuariosListarMenuItem;
    private javax.swing.JMenu usuariosMenu;
    // End of variables declaration//GEN-END:variables
}
