/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author hernanBeiza
 */
public class MenuFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    public MenuFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAgregarFono = new javax.swing.JButton();
        btnEliminarFono = new javax.swing.JButton();
        btnBuscarFono = new javax.swing.JButton();
        btnModificarFono = new javax.swing.JButton();
        btnBuscarFonoPorRut = new javax.swing.JButton();
        btnEliminarFonoPorRut = new javax.swing.JButton();
        btnMostrarCuenta = new javax.swing.JButton();
        btnMostrarCuentaSimple = new javax.swing.JButton();
        btnAplicarServicio = new javax.swing.JButton();
        btnBuscarTelefonosMarca = new javax.swing.JButton();
        btnBuscarTelefonosServicio = new javax.swing.JButton();
        btnCantidadCuentas = new javax.swing.JButton();
        btnCantidadTelefonos = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAgregarFono.setText("Agregar Fono");
        btnAgregarFono.setMaximumSize(new java.awt.Dimension(200, 30));
        btnAgregarFono.setMinimumSize(new java.awt.Dimension(200, 30));
        btnAgregarFono.setPreferredSize(new java.awt.Dimension(200, 30));
        btnAgregarFono.setSize(new java.awt.Dimension(200, 20));

        btnEliminarFono.setText("Eliminar Fono por numero");
        btnEliminarFono.setMaximumSize(new java.awt.Dimension(200, 30));
        btnEliminarFono.setMinimumSize(new java.awt.Dimension(200, 30));
        btnEliminarFono.setPreferredSize(new java.awt.Dimension(200, 30));
        btnEliminarFono.setSize(new java.awt.Dimension(200, 20));
        btnEliminarFono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarFonoActionPerformed(evt);
            }
        });

        btnBuscarFono.setText("Buscar Fono por numero");
        btnBuscarFono.setMaximumSize(new java.awt.Dimension(200, 30));
        btnBuscarFono.setMinimumSize(new java.awt.Dimension(200, 30));
        btnBuscarFono.setPreferredSize(new java.awt.Dimension(200, 30));
        btnBuscarFono.setSize(new java.awt.Dimension(200, 20));
        btnBuscarFono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarFonoActionPerformed(evt);
            }
        });

        btnModificarFono.setText("Modificar fono número");
        btnModificarFono.setMaximumSize(new java.awt.Dimension(200, 30));
        btnModificarFono.setMinimumSize(new java.awt.Dimension(200, 30));
        btnModificarFono.setPreferredSize(new java.awt.Dimension(200, 30));
        btnModificarFono.setSize(new java.awt.Dimension(200, 20));
        btnModificarFono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarFonoActionPerformed(evt);
            }
        });

        btnBuscarFonoPorRut.setLabel("Buscar fono por run/rut");
        btnBuscarFonoPorRut.setMaximumSize(new java.awt.Dimension(200, 30));
        btnBuscarFonoPorRut.setMinimumSize(new java.awt.Dimension(200, 30));
        btnBuscarFonoPorRut.setPreferredSize(new java.awt.Dimension(200, 30));
        btnBuscarFonoPorRut.setSize(new java.awt.Dimension(200, 20));
        btnBuscarFonoPorRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarFonoPorRutActionPerformed(evt);
            }
        });

        btnEliminarFonoPorRut.setText("Eliminar fono por run/rut");
        btnEliminarFonoPorRut.setMaximumSize(new java.awt.Dimension(200, 30));
        btnEliminarFonoPorRut.setMinimumSize(new java.awt.Dimension(200, 30));
        btnEliminarFonoPorRut.setPreferredSize(new java.awt.Dimension(200, 30));
        btnEliminarFonoPorRut.setSize(new java.awt.Dimension(200, 20));
        btnEliminarFonoPorRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarFonoPorRutActionPerformed(evt);
            }
        });

        btnMostrarCuenta.setText("Mostrar cuenta completa para fono");
        btnMostrarCuenta.setMaximumSize(new java.awt.Dimension(200, 30));
        btnMostrarCuenta.setMinimumSize(new java.awt.Dimension(200, 30));
        btnMostrarCuenta.setPreferredSize(new java.awt.Dimension(200, 30));
        btnMostrarCuenta.setSize(new java.awt.Dimension(200, 20));
        btnMostrarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarCuentaActionPerformed(evt);
            }
        });

        btnMostrarCuentaSimple.setText("Mostrar cuenta simple para fono");
        btnMostrarCuentaSimple.setMaximumSize(new java.awt.Dimension(200, 30));
        btnMostrarCuentaSimple.setMinimumSize(new java.awt.Dimension(200, 30));
        btnMostrarCuentaSimple.setPreferredSize(new java.awt.Dimension(200, 30));
        btnMostrarCuentaSimple.setSize(new java.awt.Dimension(200, 20));
        btnMostrarCuentaSimple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarCuentaSimpleActionPerformed(evt);
            }
        });

        btnAplicarServicio.setText("Aplicar servicio técnico a un fono");
        btnAplicarServicio.setMaximumSize(new java.awt.Dimension(200, 30));
        btnAplicarServicio.setMinimumSize(new java.awt.Dimension(200, 30));
        btnAplicarServicio.setPreferredSize(new java.awt.Dimension(200, 30));
        btnAplicarServicio.setSize(new java.awt.Dimension(200, 20));
        btnAplicarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicarServicioActionPerformed(evt);
            }
        });

        btnBuscarTelefonosMarca.setText("Buscar teléfonos asociados a una marca");
        btnBuscarTelefonosMarca.setMaximumSize(new java.awt.Dimension(200, 30));
        btnBuscarTelefonosMarca.setMinimumSize(new java.awt.Dimension(200, 30));
        btnBuscarTelefonosMarca.setPreferredSize(new java.awt.Dimension(200, 30));
        btnBuscarTelefonosMarca.setSize(new java.awt.Dimension(200, 20));
        btnBuscarTelefonosMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarTelefonosMarcaActionPerformed(evt);
            }
        });

        btnBuscarTelefonosServicio.setText("Buscar los fonos que han sido llevado a servicio técnico");
        btnBuscarTelefonosServicio.setMaximumSize(new java.awt.Dimension(200, 30));
        btnBuscarTelefonosServicio.setMinimumSize(new java.awt.Dimension(200, 30));
        btnBuscarTelefonosServicio.setPreferredSize(new java.awt.Dimension(200, 30));
        btnBuscarTelefonosServicio.setSize(new java.awt.Dimension(200, 20));
        btnBuscarTelefonosServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarTelefonosServicioActionPerformed(evt);
            }
        });

        btnCantidadCuentas.setText("Cantidad de cuentas que superan los 250 minutos");
        btnCantidadCuentas.setMaximumSize(new java.awt.Dimension(200, 30));
        btnCantidadCuentas.setMinimumSize(new java.awt.Dimension(200, 30));
        btnCantidadCuentas.setPreferredSize(new java.awt.Dimension(200, 30));
        btnCantidadCuentas.setSize(new java.awt.Dimension(200, 20));
        btnCantidadCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCantidadCuentasActionPerformed(evt);
            }
        });

        btnCantidadTelefonos.setText("Cantidad de teléfonos privados");
        btnCantidadTelefonos.setMaximumSize(new java.awt.Dimension(200, 30));
        btnCantidadTelefonos.setMinimumSize(new java.awt.Dimension(200, 30));
        btnCantidadTelefonos.setPreferredSize(new java.awt.Dimension(200, 30));
        btnCantidadTelefonos.setSize(new java.awt.Dimension(200, 20));
        btnCantidadTelefonos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCantidadTelefonosActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.setMaximumSize(new java.awt.Dimension(200, 30));
        btnSalir.setMinimumSize(new java.awt.Dimension(200, 30));
        btnSalir.setPreferredSize(new java.awt.Dimension(200, 30));
        btnSalir.setSize(new java.awt.Dimension(200, 30));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscarFonoPorRut, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                    .addComponent(btnAgregarFono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscarFono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarFono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModificarFono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarFonoPorRut, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                    .addComponent(btnMostrarCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                    .addComponent(btnMostrarCuentaSimple, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                    .addComponent(btnAplicarServicio, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                    .addComponent(btnBuscarTelefonosMarca, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                    .addComponent(btnBuscarTelefonosServicio, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                    .addComponent(btnCantidadCuentas, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                    .addComponent(btnCantidadTelefonos, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgregarFono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarFono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarFono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModificarFono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarFonoPorRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarFonoPorRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMostrarCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMostrarCuentaSimple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAplicarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarTelefonosMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarTelefonosServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCantidadCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCantidadTelefonos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarFonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarFonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarFonoActionPerformed

    private void btnBuscarFonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarFonoActionPerformed

    private void btnModificarFonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarFonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarFonoActionPerformed

    private void btnBuscarFonoPorRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFonoPorRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarFonoPorRutActionPerformed

    private void btnEliminarFonoPorRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarFonoPorRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarFonoPorRutActionPerformed

    private void btnMostrarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMostrarCuentaActionPerformed

    private void btnMostrarCuentaSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarCuentaSimpleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMostrarCuentaSimpleActionPerformed

    private void btnAplicarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAplicarServicioActionPerformed

    private void btnBuscarTelefonosMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarTelefonosMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarTelefonosMarcaActionPerformed

    private void btnBuscarTelefonosServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarTelefonosServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarTelefonosServicioActionPerformed

    private void btnCantidadCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCantidadCuentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCantidadCuentasActionPerformed

    private void btnCantidadTelefonosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCantidadTelefonosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCantidadTelefonosActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarFono;
    private javax.swing.JButton btnAplicarServicio;
    private javax.swing.JButton btnBuscarFono;
    private javax.swing.JButton btnBuscarFonoPorRut;
    private javax.swing.JButton btnBuscarTelefonosMarca;
    private javax.swing.JButton btnBuscarTelefonosServicio;
    private javax.swing.JButton btnCantidadCuentas;
    private javax.swing.JButton btnCantidadTelefonos;
    private javax.swing.JButton btnEliminarFono;
    private javax.swing.JButton btnEliminarFonoPorRut;
    private javax.swing.JButton btnModificarFono;
    private javax.swing.JButton btnMostrarCuenta;
    private javax.swing.JButton btnMostrarCuentaSimple;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
